version: "3.7"

services:
  technews:
    build: .
    env_file: .env
    environment:
      MONGODB_URI: "mongodb://root:example@mongo:27017/"
      MONGODB_DBNAME: "technews_bot"
    depends_on:
      - "mongo"

  mongo:
    profiles: ["database"]
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    profiles: ["database"]
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
